# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('variable', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('a', models.IntegerField()),
            ],
        ),
    ]
