# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfam', '0002_remove_visitlog_a'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VisitLog',
            new_name='CfamVisitLog',
        ),
    ]
