# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfam', '0003_auto_20170628_2005'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CfamVisitLog',
        ),
    ]
